DNA = "ACTGTGCTGACTCCCGGTGCTGCCGCTGCCATAGCTAAAGCCCGGGTCCTGGTAGGCAGGCGGGAAGCAGGGTGGGGGTCCCGGGTACTGGTAGGGGTAGCCCTGACCCAGAGGCGGGGGGGCAGCCGGGTGGGGCAGCGGGGCCAGCGTGTCCTGAA-CGAAGTCCCACTGGAGCCACTGTTGAGGTTCAGGGTGGCGAGATCTGGCGGNNNAGGGTAGGTGAGGGCCGCGGAGGGGCCTCCGGCGTTCCCCTCCCCCCCGCCCTGAAACCCGAAGCCCCCACTCACTGCTGCAGAGATCCCCTGAAAACGTAGTAGCACTGCTCgagacAGGTGATCTGTTGACCTGAAACCGCAGGAAGCCGTGCTTCAGCAAGCTGCTGGCGTACTTCCGGGCCT---GCCGCTCCTTGAAGCCCTCCACGTGTGTGTACAGCCAGTCCACCACGTCCGCCCCTGGCCGGCACCAGCGGTCAGCCCGCAGCCTCGAGGCAAGCAGCCCTGCCNNTGGCACTATCCGC-CGCGGGGACGGCCACTCACCGATGACGGCATNNGCGATGGTGATCTTGAGCCACATGCGGTCGCGGATCTCCAGTCCCGAG---GGCAGCTGCATGACCCGGACGACGGCGCTCATGTCACtcaccgtcagcggcgcctcttccagCCAGCTCTGCAAAGCACAGACAGCCCCGCTTCGCCCCAGCATCTGAAAGCGGGGGACTCggcAcgCTGCACCCCCAGGGGAGCCTCTGGGCAGAGCCTGCGCCAGGGCGCAAGCTGGACGGTGCGTGACAGCAGGGCCCCGGCCCACTGCAGGATGCACCCCCGTGAGGCTGGGGCGTGAGCAGGGGGGTTGGACAtttAGTCTCCCACTTCTACAGACACTTTTCATCAGGATCCTAGGCACAAACTGGGCTGAAACCCCACCCTGCAGACCAGGAAGTAATGAGAACAGGGCAGGCCCCTTCCCCTCNNCGCATGCC-CACCCGAGAGCGCAGGCTGTTAGTCGTGTTAATGGCAGGAAGCAGAATGGAGACCTGGCCCCTGCCTCTGAA-CCGTGGGTGCTCaactggctaGCCCTACGTACATCCCCTGTTCcggCCAACACACAGACATGAGCAGGATGGGCTGCACAAGGTGGGCACGGGTGCCTGTGCACACGTCTGTGCAGGGAGTTGGGGACAGGCAACACACACGTGTCACAGCCCCATGACGGggcaattgcGCCATGCTGGCTGAATGGCAGAGACGCCCCTCCAAGCCTCGGTTTCTGCTGGGGCCCTCAGGAGCTGCCACTTACGTGGAGCACCAGGCACGGAGCTGGTTAGTGAGGAGGAGCTGGTGCGCGTGACGGCGCTGGAGCAGGGACTCGTACCGTAGCGGGGCAGGGCNNNTGTCAGTGCCGCCGTGTGGtcagcggcgatCGGCG-GGTCGATGGGCCGCACCGGGTCAGCTGGGTGNAGACACGTGGCGATGACAGGCGGACAGATGGACAGGGTGGGAGGGCAGGGTGCAGGGCACAGAGGAGAGAGGCCTTCAGGCTAGGTAGGCGCCCCCTCCCCATCCCGccccGTGTGCCCCGAGGGCCACTCACCCCGTGGGACGGTGAAGTAGCTTCG-GGCGTTGGGTCCAGCACTTGGCCACAGTGAGGCTGNAAATGGCTGCAGGAACGGTGGTCCCCCCGCAAGGCCCCCATGGTCCCACCTCCCTGCCTGGCCCCTCCCGCTCCAGCGCCNCCAGCC"
print("Wyświetlam długość łańcucha DNA:", len(DNA))
print("*" * 36)
print("W DNA jest tyle błędów typu '-':", DNA.count("-", 0, len(DNA)))
print("W DNA jest tyle błędów typu 'N':", DNA.count("N", 0, len(DNA)))
print("*" * 36)
print("W DNA jest tyle zasad 'A':", DNA.count("A"))
print("W DNA jest tyle zasad 'T':", DNA.count("T"))
print("W DNA jest tyle zasad 'C':", DNA.count("C"))
print("W DNA jest tyle zasad 'G':", DNA.count("G"))
print("*" * 36)
print("*" * 36)
print("Teraz zadziała funkcja zmieniająca litery na duże :)", "*" * 15)
DNA  = DNA.upper()
print("W DNA jest tyle zasad 'A':", DNA.count("A"))
print("W DNA jest tyle zasad 'T':", DNA.count("T"))
print("W DNA jest tyle zasad 'C':", DNA.count("C"))
print("W DNA jest tyle zasad 'G':", DNA.count("G"))
print("*" * 36)
print("*" * 36)
print("*" * 36)
print("W DNA jest tyle sekwencji 'CTGAA-wątpliwa ostatnia A(Adenina)':", DNA.count("CTGAA-"))
DNA = DNA.replace("-", "")
print("W DNA jest tyle błędów typu '-':", DNA.count("-", 0, len(DNA)))
print("*" * 36)
DNA = DNA.replace("N", "")
print("W DNA jest tyle błędów typu 'N':", DNA.count("N", 0, len(DNA)))
print("*" * 36)
print("W kodzie DNA jest tyle łańcuchów 'GGGGGGG':", DNA.count("GGGGGGG"))
where_is_7xG = (DNA.find("GGGGGGG"))
print("GGGGGGG występuje jako", where_is_7xG, "pozycja w kodzie DNA.")
print("A teraz wyświetlam ten łańcuch DNA:", DNA[115:122])
print("*" * 36)
print("W kodzie DNA jest tyle łańcuchów 'CCCCCC':", DNA.count("CCCCCC"))
where_is_6xCr = DNA.rfind("CCCCCC")
print("CCCCCC występuje jako", where_is_6xCr, "pozycja w kodzie DNA licząc funkcją od tyłu.")
print("A teraz wyświetlam ten łańcuch DNA:", DNA[1659:1665])
print("*" * 36)
where_is_6xC = DNA.find("CCCCCC")
print("CCCCCC występuje jako", where_is_6xC, "pozycja w kodzie DNA licząc funkcją od przodu.")
print("A teraz wyświetlam ten łańcuch DNA:", DNA[250:256])
print("*" * 36)
print("Czy wszystkie litery są z pisane z dużej litery?", DNA.isupper())
"""DNA = DNA.upper()
print("*" * 15, "Teraz zadziała funkcja zmieniająca litery na duże :)", "*" * 15)
print("Czy wszystkie litery są z pisane z dużej litery?", DNA.isupper())"""
print("*" * 36)
print(DNA)
print("*" * 36)
print("W DNA jest tyle sekwencji 'GAGA':", DNA.count("GAGA"))
print("W DNA jest tyle sekwencji 'AGAG':", DNA.count("AGAG"))
DNA = DNA.replace("GAGA", "AGAG")
print("*" * 36)
print("W DNA jest tyle sekwencji 'GAGA':", DNA.count("GAGA"))
print("W DNA jest tyle sekwencji 'AGAG':", DNA.count("AGAG"))
print("*" * 36)
print("W DNA jest tyle sekwencji 'CTGAAA':", DNA.count("CTGAAA"))
print("W DNA jest tyle sekwencji 'CTGAA-wątpliwa ostatnia A(Adenina)':", DNA.count("CTGAA"))

RNA = DNA.replace("T", "U")
print(RNA)
print("*" * 36)
print("W RNA jest tyle zasad 'A':", RNA.count("A"))
print("W RNA jest tyle zasad 'U':", RNA.count("U"))
print("W RNA jest tyle zasad 'C':", RNA.count("C"))
print("W RNA jest tyle zasad 'G':", RNA.count("G"))
print("*" * 36)
print("Wyświetlam długość łańcucha RNA:", len(RNA))


