# Generated by Django 4.0.4 on 2022-05-24 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='book',
        ),
    ]
