# Generated by Django 4.0.4 on 2022-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_task_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Adam Mickiewicz', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='borrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
