# Generated by Django 4.0.4 on 2022-05-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_book_created_book_author_book_borrow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
